# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
z_to_BF <- function(z_hat) {
    .Call(`_daprcpptest_z_to_BF`, z_hat)
}

make_matrix <- function(p, anno_df) {
    .Call(`_daprcpptest_make_matrix`, p, anno_df)
}

run_torus <- function(locus_id, z_hat, anno_mat, names, prior = FALSE, do_verbose = FALSE, use_glmnet = TRUE) {
    .Call(`_daprcpptest_run_torus`, locus_id, z_hat, anno_mat, names, prior, do_verbose, use_glmnet)
}

torus_df <- function(locus_id, z_hat, anno_df, prior = FALSE, do_verbose = FALSE, use_glmnet = TRUE) {
    .Call(`_daprcpptest_torus_df`, locus_id, z_hat, anno_df, prior, do_verbose, use_glmnet)
}

#'@export
dap_torus <- function(argv) {
    .Call(`_daprcpptest_dap_torus`, argv)
}

