# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

make_matrix <- function(p, anno_df) {
    .Call(`_daprcpp_make_matrix`, p, anno_df)
}

torus_df <- function(locus_id, z_hat, anno_df, prior = FALSE, do_verbose = FALSE) {
    .Call(`_daprcpp_torus_df`, locus_id, z_hat, anno_df, prior, do_verbose)
}

torus <- function(locus_id, z_hat, anno_mat, names, prior = FALSE, do_verbose = FALSE) {
    .Call(`_daprcpp_torus`, locus_id, z_hat, anno_mat, names, prior, do_verbose)
}

